title: Food Mart
baseURL: /
params:
  landing_template: home
  palette: blue
  palettes:
    blue:
      sass:
        accent1: '#5f9dd2'
        accent2: '#758ce1'
        accent3: '#e286a9'
        gradient1: '#27a1e3'
        gradient2: '#e7232a'
    green:
      sass:
        accent1: '#54d3cf'
        accent2: '#4f92d1'
        accent3: '#8075e5'
        gradient1: '#16f4cf'
        gradient2: '#6532e5'
menu:
  footer:
    - identifier: normal8
      name: Made with Stackbit
      url: 'https://www.stackbit.com'
      weight: 4
  main:
    - identifier: Strategies
      name: Strategies
      url: /contact
      weight: 3
    - identifier: Risk
      name: Risk
      url: '#'
      weight: 4
    - identifier: Marketing
      name: Marketing
      url: '#'
      weight: 5
    - identifier: Finance
      name: Finance
      url: '#'
      weight: 6
    - identifier: GitHub
      name: GitHub
      url: '#'
      weight: 7
    - identifier: Vision
      name: Vision
      url: /vision_2
      weight: 1
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
